### PR TITLE
Added Spanish translation to strings.json

### PR DESCRIPTION
**Pull request by ff-ss**
Added locale "es" to the strings.json file.

### CODE REVIEW

**Comment by szTheory** [comment]
Looks great, thank you so much!

**Comment by ff-ss** [comment]
:) thank you @szTheory this is my first ever contribution! would you mind removing my last name?

**Comment by szTheory** [comment]
Sure thing! I even edited it out of the git commit history.

**Comment by szTheory** [comment]
@ff-ss I've just released a new version v3.4.0 that includes your translation, as well as a bunch of other new features and fixes. Thanks again for your contribution! https://github.com/szTheory/exifcleaner/releases/tag/v3.4.0

**Pull request merged**
